### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [221186/PY202309#2]
### 없는 파일
- challenge/week6/function.ipynb 
- practice/week6/function.ipynb
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 없는 PDF 파일
- project/week8/search_engine.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요

- WARNING in practice/week3/turtle
    - 30:Statement seems to have no effect	turtle.done
        - 괄호로 함수를 호출해주세요. 호출하지 않아서, 아무 기능을 하지 않습니다. 

- WARNING in project/week8/search_engine
    - 22:Unused argument 'preprocessed_query'	def calc_similarity(preprocessed_query, preprocessed_sentences):
        - 함수 내에서 해당 변수가 사용되고 있지 않습니다. 해당 매개변수를 제거하거나, 변수를 사용하도록 기능을 추가하세요. 

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in practice/week5/turtle

**Comment by 221186** [comment]
모두 해결했습니다!
